# Generated by Django 3.2 on 2021-04-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
