# Generated by Django 3.2 on 2021-04-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210421_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(default='2012-12-12', verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_by',
            field=models.CharField(default='', max_length=50),
        ),
    ]
