# Generated by Django 3.2 on 2021-04-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.CharField(blank=True, default='https://cdn.wallpapersafari.com/35/57/iUfZRE.jpg', max_length=400),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(blank=True, default='2012-12-12', verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_by',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='story_overview',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
