# Generated by Django 3.2 on 2021-04-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archetypes', '0002_alter_archetype_archetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protagonist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('character_bio', models.TextField(max_length=700)),
                ('character_archetypes', models.ManyToManyField(related_name='main_protagonist', to='archetypes.Archetype')),
            ],
        ),
    ]
