# Generated by Django 3.2 on 2021-04-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_remove_book_main_protagonist'),
        ('protagonists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protagonist',
            name='books',
            field=models.ManyToManyField(related_name='main_protagonist', to='books.Book'),
        ),
    ]
