# Generated by Django 3.2 on 2021-04-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protagonists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protagonist',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
