# Generated by Django 3.2 on 2021-04-16 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supporting_characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protagonists', '0001_initial'),
        ('genres', '0001_initial'),
        ('antagonists', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_contributor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='books_contributed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='book_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='books_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='books', to='genres.Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='main_antagonist',
            field=models.ManyToManyField(related_name='books', to='antagonists.Antagonist'),
        ),
        migrations.AddField(
            model_name='book',
            name='main_protagonist',
            field=models.ManyToManyField(related_name='books', to='protagonists.Protagonist'),
        ),
        migrations.AddField(
            model_name='book',
            name='supporting_characters',
            field=models.ManyToManyField(related_name='books', to='supporting_characters.SupportingCharacter'),
        ),
    ]
