# Generated by Django 3.2 on 2021-04-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_characters', '0002_alter_supportingcharacter_relationship_to_protagonist'),
        ('books', '0002_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='supporting_characters',
            field=models.ManyToManyField(related_name='books', to='supporting_characters.SupportingCharacter'),
        ),
    ]
