# Generated by Django 3.2 on 2021-04-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('books', '0003_book_supporting_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='books', to='genres.Genre'),
        ),
    ]
