# Generated by Django 3.2 on 2021-04-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_characters', '0001_initial'),
        ('genres', '0001_initial'),
        ('protagonists', '0001_initial'),
        ('antagonists', '0001_initial'),
        ('books', '0003_auto_20210416_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(null=True, related_name='books', to='genres.Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='main_antagonist',
            field=models.ManyToManyField(null=True, related_name='books', to='antagonists.Antagonist'),
        ),
        migrations.AlterField(
            model_name='book',
            name='main_protagonist',
            field=models.ManyToManyField(null=True, related_name='books', to='protagonists.Protagonist'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='supporting_characters',
            field=models.ManyToManyField(null=True, related_name='books', to='supporting_characters.SupportingCharacter'),
        ),
    ]
