# Generated by Django 3.2 on 2021-04-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='story_overview',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
