# Generated by Django 3.2 on 2021-04-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protagonists', '0001_initial'),
        ('supporting_characters', '0001_initial'),
        ('genres', '0001_initial'),
        ('antagonists', '0001_initial'),
        ('books', '0006_auto_20210416_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='books', to='genres.Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='main_antagonist',
            field=models.ManyToManyField(blank=True, related_name='books', to='antagonists.Antagonist'),
        ),
        migrations.AlterField(
            model_name='book',
            name='main_protagonist',
            field=models.ManyToManyField(blank=True, related_name='books', to='protagonists.Protagonist'),
        ),
        migrations.AlterField(
            model_name='book',
            name='supporting_characters',
            field=models.ManyToManyField(blank=True, related_name='books', to='supporting_characters.SupportingCharacter'),
        ),
    ]
