# Generated by Django 3.2 on 2021-04-16 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('antagonists', '0001_initial'),
        ('protagonists', '0001_initial'),
        ('genres', '0001_initial'),
        ('supporting_characters', '0001_initial'),
        ('books', '0007_auto_20210416_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_contributor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='books_contributed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='books', to='genres.Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='main_antagonist',
            field=models.ManyToManyField(related_name='books', to='antagonists.Antagonist'),
        ),
        migrations.AlterField(
            model_name='book',
            name='main_protagonist',
            field=models.ManyToManyField(related_name='books', to='protagonists.Protagonist'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='story_overview',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='supporting_characters',
            field=models.ManyToManyField(related_name='books', to='supporting_characters.SupportingCharacter'),
        ),
    ]
