# Generated by Django 3.2 on 2021-04-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_story_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
