# Generated by Django 3.2 on 2021-04-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20210416_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_contributor',
        ),
    ]
