# Generated by Django 3.2 on 2021-04-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protagonists', '0001_initial'),
        ('books', '0008_alter_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='main_protagonist',
            field=models.ManyToManyField(related_name='books', to='protagonists.Protagonist'),
        ),
    ]
