# Generated by Django 3.2 on 2021-04-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antagonists', '0001_initial'),
        ('books', '0009_book_main_protagonist'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='main_antagonist',
            field=models.ManyToManyField(related_name='books', to='antagonists.Antagonist'),
        ),
    ]
