# Generated by Django 3.2 on 2021-04-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_book_contributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_creator',
        ),
    ]
