# Generated by Django 3.2 on 2021-04-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='main_protagonist',
        ),
    ]
