# Generated by Django 3.2 on 2021-04-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_remove_book_main_protagonist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='main_antagonist',
        ),
        migrations.RemoveField(
            model_name='book',
            name='supporting_characters',
        ),
    ]
