# Generated by Django 3.2 on 2021-04-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('is_first_login', models.BooleanField(default=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('user_searches', models.CharField(max_length=50)),
                ('favourite_books', models.CharField(max_length=50)),
            ],
        ),
    ]
