# Generated by Django 3.2 on 2021-04-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('relationship_to_protagonist', models.CharField(choices=[('N/A', 'None Input'), ('FM', 'Family Member'), ('R', 'Rival'), ('L', 'Love Interest'), ('F', 'Friend'), ('C', 'Companion'), ('A', 'Ally'), ('E', 'Enemy'), ('SER', 'Servant')], default='N/A', max_length=10)),
            ],
        ),
    ]
