# Generated by Django 3.2 on 2021-04-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingcharacter',
            name='relationship_to_protagonist',
            field=models.CharField(choices=[('None Input', 'None Input'), ('Family Member', 'Family Member'), ('Rival', 'Rival'), ('Love Interest', 'Love Interest'), ('Friend', 'Friend'), ('Companion', 'Companion'), ('Ally', 'Ally'), ('Enemy', 'Enemy'), ('Servant', 'Servant'), ('Mentor', 'Mentor')], default='None Input', max_length=50),
        ),
    ]
