# Generated by Django 3.2 on 2021-04-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archetypes', '0001_initial'),
        ('supporting_characters', '0003_auto_20210415_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingcharacter',
            name='character_archetypes',
            field=models.ManyToManyField(related_name='SupportingCharacters', to='archetypes.Archetype'),
        ),
    ]
