# Generated by Django 3.2 on 2021-04-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archetypes', '0002_alter_archetype_archetype'),
        ('supporting_characters', '0004_supportingcharacter_character_archetypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingcharacter',
            name='character_archetypes',
            field=models.ManyToManyField(related_name='supporting_characters', to='archetypes.Archetype'),
        ),
    ]
