# Generated by Django 3.2 on 2021-04-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_characters', '0005_alter_supportingcharacter_character_archetypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingcharacter',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
